---

- name: Say Hello
  hosts: servers
  tasks:
  - name: sayIt
    ansible.builtin.include_role:
      name: basic
      tasks_from: say_it.yml
      apply:
        become: true
    vars:
      name: "{{ secret_name }}"
